services:
  db:
    image: mariadb:10.5
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=$DB_USER
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.6.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$DB_USER
      - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:    
    depends_on:      
      - webserver    
    image: certbot/certbot    
    container_name: certbot    
    volumes:      
      - certbot-etc:/etc/letsencrypt      
      - wordpress:/var/www/html    
    command: certonly --webroot --webroot-path=/var/www/html --email borenmon5@gmail.com --agree-tos --no-eff-email --staging -d boren-do-v1.online -d boren-do-v1.online

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
